version: '3'
services:
  ros2:
    container_name: ros2-humble
    image: osrf/ros:humble-desktop-full  # 이미지 사용
    networks:
      - dev-network
    ports:
      - "11311:11311" # ROS2 기본 포트
  flutter:
    container_name: flutter-dev
    image: ghcr.io/cirruslabs/flutter:latest  # 이미지 사용
    networks:
      - dev-network
    ports:
      - "8080:8080" # Flutter 웹 서버 포트
networks:
  dev-network:
    driver: bridge
